### ISSUE TITLE
Installed but settings shows error and does not show when keyboard pulls up

### ISSUE THREAD

**Issue by BenjaminCCross** [8a1wkar/DockX13#1]
Running on IOS 13.5
IPhone XS

![IMG_5750](https://user-images.githubusercontent.com/21342404/83813053-a01a5780-a68a-11ea-9194-518c8aba17a6.JPEG)

![IMG_5751](https://user-images.githubusercontent.com/21342404/83813262-04d5b200-a68b-11ea-957f-67fa4bbc57d4.JPEG)

**Comment by 8a1wkar** [comment]
Install cephei tweak and respring your devices.

**Comment by BenjaminCCross** [comment]
Looks like it worked! Thanks
